apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjob-{{ .Chart.Name }}-{{ .Values.CRONJOB_NAME}}
spec:
  schedule: {{.Values.CRONJOB_SCHEDULE}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
        spec:
          volumes:
            - name: "{{ .Values.PERSISTENT_STORAGE_NAME }}"
              persistentVolumeClaim:
                claimName: "{{ .Values.PERSISTENT_STORAGE_NAME }}"
            - name: lagoon-sshkey
              secret:
                defaultMode: 420
                secretName: lagoon-sshkey
          containers:
          - name: cronjob-{{ .Chart.Name }}-{{ .Values.CRONJOB_NAME}}
            image: "{{ .Values.image.repository }}"
            command:
              - /lagoon/cronjob.sh
              - "${CRONJOB_COMMAND}"
            volumeMounts:
            - name: "{{ .Values.PERSISTENT_STORAGE_NAME }}"
              mountPath: "{{ .Values.PERSISTENT_STORAGE_PATH }}"
            envFrom:
            - configMapRef:
                name: lagoon-env
            env:
              - name: LAGOON_GIT_SHA
                value: "{{.Values.LAGOON_GIT_SHA}}"
              - name: SERVICE_NAME
                value: "{{.Values.SERVICE_NAME}}"
            volumeMounts:
              - name: "{{ .Values.PERSISTENT_STORAGE_NAME }}"
                mountPath: "{{ .Values.PERSISTENT_STORAGE_PATH }}"
              - mountPath: /var/run/secrets/lagoon/sshkey/
                name: lagoon-sshkey
                readOnly: true
          restartPolicy: OnFailure 